export const surpriseMePrompts = [
  "A beach at sunset with palm trees in the foreground",
  "An abandoned spaceship floating in space",
  "A bustling city street at night with lights and people",
  "A cozy cabin in the woods with a fire burning in the fireplace",
  "A dragon flying over a castle at night",
  "A futuristic city skyline with flying cars",
  "A majestic mountain range with snow-capped peaks",
  "A mystical forest with a unicorn grazing",
  "A serene lake with a cabin in the distance",
  "An underwater scene with colorful coral and schools of fish",
  "A wild west saloon with cowboys and a poker game in progress",
  "A zen garden with rocks and sand patterns",
  "A haunted mansion with lightning and a full moon in the background",
  "An ice cream truck parked on a sunny street corner",
  "A rainbow over a waterfall in a lush jungle",
  "A castle on a hilltop with a moat and drawbridge",
  "An enchanted garden with a fountain and a maze",
  "A futuristic space station orbiting a planet",
  "A hot air balloon flying over a mountain range",
  "A jungle with a river and a waterfall",
  "A medieval village with thatched-roof cottages",
  "A modern skyscraper skyline at sunrise",
  "A peaceful countryside with rolling hills and farms",
  "A pirate ship on the high seas with a Jolly Roger flag",
  "A rainbow-colored hot air balloon festival",
  "A snowy forest with a cabin in the clearing",
  "A spaceship docking at a futuristic spaceport",
  "A tropical island with palm trees and a white sand beach",
  "An underwater city with mermaids and sea creatures",
  "A wizard's tower on a rocky mountaintop",
]
